### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by yusufobr** [zunairkhan811/Awesome-booksES6-using-modules#2]
Hi @zunairkhan811, kindly make sure to use Uppercase on the first letter of `Classes`
https://github.com/zunairkhan811/Awesome-booksES6-using-modules/blob/b9172798b0f1d1bc44078ce4ad4c2befeb67fcad/modules/store_module.js#L1-L25

**Comment by zunairkhan811** [comment]
Hi! I appreciate your suggestion. The changes said have been done in the code.
